/*
Copyright 2007 Security Compass

This file is part of SQL Inject Me.

Access Meis free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Access Meis distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SQL Inject Me.  If not, see <http://www.gnu.org/licenses/>.

If you have any questions regarding Access Meplease contact
tools@securitycompass.com
*/

#include "nsISupports.idl"
#include "nsIFile.idl"
#include "nsIWritablePropertyBag2.idl"

/**
 * 
 */

[scriptable, uuid(5b4ef7bb-b996-4310-9a12-842f454313e3)]
interface SecCompIPreferenceContainer: nsISupports {
    void getContents(out unsigned long length, [retval, array, size_is(length)] out nsIWritablePropertyBag2 contents);
    boolean addString(in string str, in string sig);
    boolean save();
    boolean swap(in unsigned long index1, in unsigned long index2);
    boolean exportToFile(in nsIFile file);
    boolean importFromFile(in nsIFile file);
    boolean remove(in long index);
};

