/* Copyright (c) 2006 SecurityCompass
   See the file LICENSE.txt for licensing information. */

#include "nsISupports.idl"
#include "SecCompISpecificPreferenceContainer.idl"
#include "SecCompIXMLExportable.idl"
#include "SecCompIPreferenceContainer.idl"

/**
 * Defines how to store, ace
 */

[scriptable, uuid(e69088c0-4474-4ee1-962d-7c2479dd8f7b)]
interface SecCompIPassRegexContainer:nsISupports
{
    /* nothing new, just an aggregate for it's ancestors */
};

