/*
Copyright 2007 Security Compass

This file is part of Access Me.

Access Meis free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Access Meis distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Access Me.  If not, see <http://www.gnu.org/licenses/>.

If you have any questions regarding Access Meplease contact
tools@securitycompass.com
*/


#include "nsISupports.idl"

/**
 * used to tell the SecCompIGenericPrferenceContainers the specifics of the
 * preferences they're going to be working on.
 */

[scriptable, uuid(3b336393-46a3-4a05-bbb8-f88b4efc3064)]
interface SecCompISpecificPreferenceContainer: nsISupports {
    /**
     * The pref name. The last chars of the pref from the last dot (exclusive)
     */
    string getPrefName();
    /**
     * the branch name. chars from begining to last dot (inclusive).
     */
    string getBranchName();
};

